import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* 
          This script runs synchronously before React hydration.
          It prevents the browser from restoring the previous scroll position,
          which would cause Framer Motion's useScroll to initialize at ~1.0
          and render the last frame on page load.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (history.scrollRestoration) history.scrollRestoration = 'manual';
                window.scrollTo(0, 0);
              } catch(e) {}
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
